config/routes.rb
Gratefuldeed::Application.routes.draw do
  resources :stories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'home/how_it_works'
  get 'home/deeds'
  get 'home/about'
  get 'home/contactus'
  post 'home/contactus'
  get 'home/privacy'
  get 'home/faq'
  get 'home/wall'
  
  resources :deeds do
    member do
      get 'purchase'
    end
  end
  resources :sponsors
  resources :charities
  resource  :dashboard
  resources  :purchases do
    collection do
      get 'success'
    end
  end
  
  namespace :admin do
    resource :dashboard
    resources :users
    resources  :purchases
    resources :giveons
    resources :deeds do
      member do
        get 'activate'
        get 'cancel'
        get 'freeze'
        get 'spotify'
      end
    end
    resources :stories
    resources :sponsors do
      member do
        get 'verify'
        get 'deny'
      end
    end
    resources :charities
    
  end
  
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_left.html.erb
<div class="leftsec_topwrap">
	<div class="leftsec_btmwrap">
    	<div class="leftsec_midwrap">
        	<div class="leftmenu">
			   <h5>Quick Links</h5>
			   <ul>
			   	<li><%= link_to "How it Works", home_how_it_works_url%></li>
			   	<li><%= link_to "My Benefactor Wall", home_wall_url %></li>
			   	<li><%= link_to "Tell Friends", ""%></li>
			   	<li><%= link_to "Create a Grateful Deed", new_deed_url%></li>
        	   
			     <% if user_signed_in? && !current_user.is_a_charity? %>
			     <li><%= link_to "This is a charity account", new_charity_url %></li>
			     <% end %>
        	   
			     <li><%= link_to "Sponsors", sponsors_url%></li>
			   	<li><%= link_to "Charities", charities_url%></li>
			     <li><%= link_to "Current Deeds", home_deeds_url%></li>
			   </ul>
			</div>
			
			<%= admin_area do  %>
				<h5 class="orange">Admin Menu</h5>
				<ul>
				<li><%= link_to "Deeds", admin_deeds_url%></li>
				<li><%= link_to "Purchases", admin_giveons_url%></li>
				<li><%= link_to "Sponsors", admin_sponsors_url%></li>
				<li><%= link_to "Charities", admin_charities_url%></li>
				<li><%= link_to "Success Stories", admin_stories_url%></li>
				</ul>
			<% end %>
			<%= sponsor_area do %>
				<h5 class="green">Sponsor's Menu</h5>
				<ul>
					<li><%= link_to "Grateful Deeds", deeds_url%></li>
				<li><%= link_to "Create a Grateful Deed", new_deed_url%></li>
				</ul>
			<% end %>
        </div><!--end of leftsec_midwrap-->
    </div><!--end of leftsec_btmwrap-->
</div><!--end of leftsec_topwrap-->

app/views/shared/_right.html.erb
<div class="rightsec">
	<div class="give_ons">
        <%= render_cell :give_on, :display %>
    </div><!--end of give_ons-->

	<div class="stories_topwrap">
    	<div class="stories_btmwrap">
        	<div class="stories_midwrap">

            	<%= render_cell :success_story, :display %>
				
				<p class="button"><%= link_to image_tag("/images/button_viewallstories.png", :width=> 185, :height=>29, :border=>0), stories_path %></p>
				
            </div><!--end of stories_midwrap-->
        </div><!--end of stories_btmwrap-->
    </div><!--end of sotries_topwrap-->
</div><!--end of rightsec-->