config/routes.rb
Gratefuldeed::Application.routes.draw do
  resources :stories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'home/how_it_works'
  get 'home/deeds'
  get 'home/about'
  get 'home/contactus'
  post 'home/contactus'
  get 'home/privacy'
  get 'home/faq'
  get 'home/wall'
  
  resources :deeds do
    member do
      get 'purchase'
    end
  end
  resources :sponsors
  resources :charities
  resource  :dashboard
  resources  :purchases do
    collection do
      get 'success'
    end
  end
  
  namespace :admin do
    resource :dashboard
    resources :users
    resources  :purchases
    resources :giveons
    resources :deeds do
      member do
        get 'activate'
        get 'cancel'
        get 'freeze'
        get 'spotify'
      end
    end
    resources :stories
    resources :sponsors do
      member do
        get 'verify'
        get 'deny'
      end
    end
    resources :charities
    
  end
  
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, :except => :wall
  
  def index
    @spotlight = Spotlight.first
    unless @spotlight.nil?
      @contribution = @spotlight.deed.price + @spotlight.deed.contribution
    end
    @donations = Purchase.paid.order("created_at DESC").page(params[:page]).per(3)
    if user_signed_in?
      if current_user.is_admin?
        redirect_to admin_dashboard_path
      else
        redirect_to "/dashboard"
      end
    end
  end
  
  def deeds
    @deeds = Deed.active.active.page(params[:page]).per(10)
  end
  
  def contactus
    unless params[:email].nil?
      ContactUs::contact_email.deliver(params[:email])
    end
  end
  
  def wall
    @benefactors = current_user.purchases.pending
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="conwrap">
	<h2>What is Grateful Deed?</h2>
	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
</div>

app/views/home/contactus.html.erb
<div class="contactus">
	<div class="form_heading">
    	<h5>Contact Us</h5>
    </div><!--end of form_heading-->
    <div class="form_leftwrap">
    	<div class="form_rightwrap">
        	<div class="form_midwrap">
            	<%= form_for :email, :url => { :controller => 'home', :action => 'contactus' } do |f| %>
                	<label>Full Name:</label>
                    <div class="textbox_wrapper">
                    	<%= f.text_field :name, :class => "textbox" %>
                    </div><!--end of textbox_wrapper-->
					<label>Email Address:</label>
                    <div class="textbox_wrapper">
                    	<%= f.text_field :address, :class => "textbox" %>
                    </div><!--end of textbox_wrapper-->
					<p class="infonote">We promise not to share your email address to others.</p>
					<label>Subject:</label>
                    <div class="textbox_wrapper">
                    	<%= f.text_field :subject, :class => "textbox" %>
                    </div><!--end of textbox_wrapper-->
					<label>Your Message:</label>
					<div class="textarea_wrapper">
						<%= f.text_area :body, :rols => 10, :cols => 60 %>
					</div><!--end of textarea_wrapper-->
                    <div class="form_btmwrap">
                        <input type="image" src="/images/button_sendmail.png" alt="Send Email" class="button" />
                        <div class="clear"></div><!--end of clear-->
                    </div><!--end of form_btmwrap-->
                <% end %>
            </div><!--end of form_midwrap-->
        </div><!--end of form_rightwrap-->
    </div><!--end of form_leftwrap-->
</div><!--end of contactus-->

app/views/home/deeds.html.erb
<h1>Current Deeds</h1>
<div id="deeds">
  <ul>
  <% @deeds.each do |deed| %>
    <li>
		<%= link_to deed.sponsor.name, sponsor_path(deed.sponsor) %> donated <%= number_to_currency deed.amount %> to <%= link_to deed.charity.name, charity_path(deed.charity) %>
		<%= link_to "Buy Deed", purchase_deed_path(deed)%>
	</li>
  <% end %>
  </ul>
</div>

app/views/home/faq.html.erb
<div class="conwrap">
	<h2>Frequently Asked Questions</h2>
</div>

app/views/home/how_it_works.html.erb
<div class="conwrap">
	<h2>Privacy Policy</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
</div>

app/views/home/index.html.erb
<% unless @spotlight.nil? %>
<div class="greycontainer_topwrap">
  <div class="greycontainer_btmwrap">
      <div class="greycontainer_midwrap">
          <div class="timeremaining_wrap">
              <div class="wrapper">
                  <h4><div id="countdown"></div></h4>
                    <p>Remaining Time</p>
                </div><!--end of wrapper-->
            </div><!--end of timeremaingin_wrap-->
            <h3 class="countdown_title">CURRENT <span>DEED</span></h3>
			<%= link_to "Click_HERE_to_Buy_Deed", purchase_deed_path(@spotlight.deed), :class => "countdown_button"%>
            <div class="clear"></div><!--end of clear-->
        </div><!--end of greycontainer_midwrap-->
    </div><!--end of greycontainer_btmwrap-->
</div><!--end of greycontainer_topwrap-->
  
<div class="greycontainer_topwrap">
  <div class="greycontainer_btmwrap">
      <div class="greycontainer_midwrap">
          <div class="donationpurchase_midwrap">
              <div class="donationpurchase_topwrap">
                  <div class="donationpurchase_btmwrap">
                      <div class="amountbox_topwrap">
                          <div class="amountbox_btmwrap">
                              <div class="amountbox_midwrap">
                                  <p><%= number_to_currency @spotlight.deed.price %> </p>
                                </div><!--end of amountbox_midwrap-->
                            </div><!--end of amountbox_btmwrap-->
                        </div><!--end of amountbox_topwrap-->
                        <div class="textwrapper">
                          <p>Your Donation Purchase</p>
                        </div><!--end of textwrapper-->
                      <div class="clear"></div><!--end of clear-->
                    </div><!--end of donationpurchase_btmwrap-->
                </div><!--end of donationpurchase_topwrap-->
            </div><!--end of donationpurchase_midwrap-->
            <div class="donationpurchase_imgwrap">
              <img src="/images/sample_pic1.jpg" alt="" />
            </div><!--end of donationpurchase_imgwrap-->
            <div class="clear"></div><!--end of clear-->
            <div class="signwrap">
              <img src="/images/img_plus.png" alt="" width="24" height="24" />
            </div><!--end of signwrap-->
            <div class="clear"></div><!--end of clear-->
            <div class="matchingcon_midwrap">
              <div class="matchingcon_topwrap">
                  <div class="matchingcon_btmwrap">
                      <div class="amountbox_topwrap">
                          <div class="amountbox_btmwrap">
                              <div class="amountbox_midwrap">
                                  <p><%= number_to_currency @spotlight.deed.contribution %></p>
                                </div><!--end of amountbox_midwrap-->
                            </div><!--end of amountbox_btmwrap-->
                        </div><!--end of amountbox_topwrap-->
                        <div class="textwrapper">
                          <p>Will generate a matching contribution from sponsor in this amount</p>
                        </div><!--end of textwrapper-->
                      <div class="clear"></div><!--end of clear-->
                    </div><!--end of matchingcon_btmwrap-->
                </div><!--end of matchingcon_topwrap-->
            </div><!--end of matchingcon_midwrap-->
            <div class="matchingcon_imgwrap">
              <%= image_tag @spotlight.deed.sponsor.user.logo.url %>
            </div><!--end of matchingcon_imgwrap-->
            <div class="clear"></div><!--end of clear-->
            <div class="signwrap">
              <img src="/images/img_equal.png" alt="" width="24" height="24" />
            </div><!--end of signwrap-->
            <div class="clear"></div><!--end of clear-->
            <div class="charityrecieved_midwrap">
              <div class="charityrecieved_topwrap">
                  <div class="charityrecieved_btmwrap">
                      <div class="amountbox_topwrap">
                          <div class="amountbox_btmwrap">
                              <div class="amountbox_midwrap">
                                  <p><%= number_to_currency @contribution %></p>
                                </div><!--end of amountbox_midwrap-->
                            </div><!--end of amountbox_btmwrap-->
                        </div><!--end of amountbox_topwrap-->
                        <div class="textwrapper">
                          <p>Total amount recieved by charity</p>
                        </div><!--end of textwrapper-->
                      <div class="clear"></div><!--end of clear-->
                    </div><!--end of charityrecieved_btmwrap-->
                </div><!--end of charityrecieved_topwrap-->
            </div><!--end of charityrecieved_midwrap-->
            <div class="charityrecieved_imgwrap">
              <%= image_tag @spotlight.deed.charity.user.logo.url %>
            </div><!--end of charityrecieved_imgwrap-->
            <div class="clear"></div><!--end of clear-->
			<%= link_to image_tag("/images/button_clickhereformoredetails.png", :alt => "Click here for MORE DETAILS"), deed_path(@spotlight.deed)%>
        </div><!--end of greycontainer_midwrap-->
    </div><!--end of greycontainer_btmwrap-->
</div><!--end of greycontainer_topwrap-->
<% end %>
<% unless @donations.blank? %>
<div class="lupdates_midwrap">
  <div class="lupdates_btmwrap">
      <div class="lupdates_topwrap">
          <div class="colleft">
              <img src="/images/txtimg_latestupdates.png" alt="Latest Updates" width="26" height="184" />
            </div><!--end of colleft-->
            <div class="colright">
			
			  <% @donations.each do |donation| %>
              <div class="profilepic_wrap">
				  <%= image_tag donation.user.logo.url, :width => 58, :height => 55%>
                </div><!--end of profilepic_wrap-->
                <div class="lupdates_contentwrap">
                  <p><a href="#" class="donor"><%= donation.user.name %></a> bought <%= number_to_currency donation.amount %> give-on for <a href="#" class="charity"><%= donation.deed.charity.name %></a> sponsored by <a href="#" class="sponsor"><%= donation.deed.sponsor.name %></a>...</p>
                    <p class="date"><%= donation.created_at.strftime "%m-%d-%Y" %></p>
                </div><!--end of lupdates_contentwrap-->
              <div class="clear"></div><!--end of clear-->
			  <% end %>
			
			
              <div class="clear"></div><!--end of clear-->
            </div><!--end of colright-->
          <div class="clear"></div><!--end of clear-->
        </div><!--end of lupdates_topwrap-->
    </div><!--end of lpudates_btmwrap-->
</div><!--end of lupdates_midwrap-->
<% end %>

app/views/home/privacy.html.erb
	<div class="conwrap">
		<h2>Privacy Policy</h2>
		<p>Phasellus blandit viverra egestas. Duis lectus enim, posuere in suscipit vel, aliquam sit amet purus. Vestibulum quis lorem diam. Suspendisse potenti. Etiam et dapibus lacus. Curabitur at leo augue, eu placerat mauris. Morbi dictum nulla at velit eleifend at sagittis eros ornare. Morbi eu nisi eu magna ornare mollis. Fusce tempus ipsum in elit sodales commodo adipiscing in mauris. Donec dictum semper justo, eget tincidunt leo pellentesque at. Integer in ante lacus. Fusce sagittis justo ac ligula consectetur quis fermentum arcu lacinia. Quisque vitae sem ut velit placerat laoreet. Donec feugiat diam nec nunc tempor semper sit amet et nisl.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nunc metus, lacinia volutpat placerat id, lacinia non urna. Phasellus sed pellentesque felis. Praesent a pretium mauris. Praesent mattis, enim ac tempus iaculis, orci felis lobortis augue, eget dictum tellus lacus sit amet nisi. Duis semper, dolor ac adipiscing faucibus, ligula massa pharetra libero, nec auctor metus mi eu leo. Aliquam vitae dolor at nisi auctor dictum sed sit amet dui. Sed interdum purus turpis. Nulla dolor metus, porta et elementum pretium, placerat vitae orci. Nam vulputate tellus nisl, sit amet convallis sapien. Aenean ac scelerisque sapien. Nulla mauris lectus, facilisis at volutpat quis, gravida eu mi. In hac habitasse platea dictumst. Sed quis metus felis, vestibulum viverra magna. Nam in urna id mauris tempor mattis. Aenean volutpat elit consectetur velit pharetra luctus. Morbi iaculis vehicula arcu ac consequat. Curabitur vulputate molestie nisi quis pretium. Suspendisse laoreet elit sed elit ultricies pretium. Mauris pharetra posuere ipsum, ac posuere nisl laoreet sed.</p>
		<p>Sed justo lectus, egestas eget interdum sit amet, convallis a dui. Aliquam ligula arcu, tincidunt ut cursus et, pretium accumsan urna. Aliquam feugiat suscipit sapien sed tincidunt. Maecenas in massa nisl, sit amet posuere dolor. Nunc augue sem, malesuada vel porttitor id, varius non nisi. Etiam bibendum aliquet ante in dapibus. Sed accumsan semper nibh ac luctus. Curabitur accumsan tempus enim a sollicitudin. Donec porttitor tempor interdum. Nam in ligula at elit sagittis euismod vitae eu mi. Aliquam eget mauris nunc. Phasellus et turpis est. Morbi eget vulputate lectus. Phasellus consectetur egestas tortor, eget interdum turpis tempus sit amet. Maecenas orci orci, dapibus nec consectetur eu, semper ut felis. Ut justo nisi, tincidunt eget scelerisque vel, tempor in quam. Ut euismod nulla et tellus scelerisque vestibulum a in quam. Phasellus laoreet mi eu urna facilisis convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at eleifend urna. </p>
	</div>

app/views/home/wall.html.erb
<h1>Benefactor Wall</h1>
<div class="benefactors">
	<ul>
		<% @benefactors.each do |benefactor| %>
		<li>
		  <%= image_tag(benefactor.deed.charity.user.logo.url) %>
		  <%= image_tag(benefactor.deed.sponsor.user.logo.url) %>
		  <%= benefactor.created_at.strftime("%m/%d/%Y") %>
		  <p>
			<%= benefactor.name %> donated <%= number_to_currency benefactor.amount%> to trigger <%= number_to_currency benefactor.deed.amount %> to Charity. Sponsored by <%= benefactor.deed.sponsor.name %>.
		  </p>
		</li>
		<% end %>
	</ul>
</div>