config/routes.rb
Gratefuldeed::Application.routes.draw do
  resources :stories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'home/how_it_works'
  get 'home/deeds'
  get 'home/about'
  get 'home/contactus'
  post 'home/contactus'
  get 'home/privacy'
  get 'home/faq'
  get 'home/wall'
  
  resources :deeds do
    member do
      get 'purchase'
    end
  end
  resources :sponsors
  resources :charities
  resource  :dashboard
  resources  :purchases do
    collection do
      get 'success'
    end
  end
  
  namespace :admin do
    resource :dashboard
    resources :users
    resources  :purchases
    resources :giveons
    resources :deeds do
      member do
        get 'activate'
        get 'cancel'
        get 'freeze'
        get 'spotify'
      end
    end
    resources :stories
    resources :sponsors do
      member do
        get 'verify'
        get 'deny'
      end
    end
    resources :charities
    
  end
  
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  belongs_to :user
  has_many :deeds
  validates_presence_of :address, :name, :state, :city, :zipcode, :contact_phone
  
  scope :active, lambda {
    where("is_verified = true")
  }
  
  def deny
    update_attributes(:is_verified => false)
  end
  
  def verify
    update_attributes(:is_verified => true)
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < Admin::BaseController
  
  def index
    @sponsors = Sponsor.page(params[:page]).per(10)
  end
  
  def verify
    @sponsor = Sponsor.find(params[:id])
    @sponsor.verify
    SponsorMailer::account_verified(@sponsor).deliver
  end
  
  def deny
    @sponsor = Sponsor.find(params[:id])
    @sponsor.deny
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @sponsors = Sponsor.active.page(params[:page]).per(10)
  end
  
  def new
    @sponsor = Sponsor.new
  end
  
  def create
    @sponsor = Sponsor.new(params[:sponsor])
    @sponsor.user = current_user
    if @sponsor.save
      flash[:info] = "Your application is successfully submitted. You'll receive a verification email once your application is verified."
      redirect_to dashboard_path
    else
      flash.now[:error] = @sponsor.errors.full_messages.first
      render :action => 'new'
    end
  end
  
  def show
    @sponsor = Sponsor.find(params[:id])
    @deeds = @sponsor.deeds.completed.page(params[:page]).per(10)
  end
  
  def edit
    @sponsor = Sponsor.find(params[:id])
  end
end

app/helpers/admin/sponsors_helper.rb
module Admin::SponsorsHelper
end

app/helpers/sponsors/dashboard_helper.rb
module Sponsors::DashboardHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/admin/sponsors/deny.js.erb
$('#status_<%= @sponsor.id%>').html('nope <%= link_to "Verify", verify_admin_sponsor_path(@sponsor), 'data-remote' => true, 'data-method' => 'get' unless @sponsor.is_verified %>');

app/views/admin/sponsors/index.html.erb
<h2>Sponsors</h2>
<table>
  <thead>
	<tr>
		<th>Name<th>
		<th>Address<th>
		<th>City<th>
		<th>Zipcode<th>
		<th>Contact Name<th>
		<th>Contact Phone<th>
		<th>Business Phone<th>
		<th>Verified<th>
	</tr>
  </thead>
  <tbody>
  <% @sponsors.each do |sponsor| %>
	<tr class="<%= cycle "even", "odd" %>">
	  <td><%= sponsor.name %><td>
	  <td><%= sponsor.address %><td>
	  <td><%= sponsor.city %><td>
      <td><%= sponsor.zipcode %><td>
      <td><%= sponsor.contact_name %><td>
	  <td><%= sponsor.contact_phone %><td>
	  <td><%= sponsor.business_phone %><td>
	  <td>
	    <div id="status_<%= sponsor.id%>">
		  <%= sponsor.is_verified ? 'yes' : 'nope' %>
		  <%= link_to "Verify", verify_admin_sponsor_path(sponsor), 'data-remote' => true, 'data-method' => 'get' unless sponsor.is_verified %>
		  <%= link_to "Deny", deny_admin_sponsor_path(sponsor), 'data-remote' => true, 'data-method' => 'get' if sponsor.is_verified %>
		<div>
	  </td>
	</tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr>
	  <td colspan=9><%= paginate @sponsors %><td>
	</tr>
  </tfoot>
</table>

app/views/admin/sponsors/verify.js.erb
$('#status_<%= @sponsor.id%>').html('yes <%= link_to "Deny", deny_admin_sponsor_path(@sponsor), 'data-remote' => true, 'data-method' => 'get' if @sponsor.is_verified %>');