config/routes.rb
Gratefuldeed::Application.routes.draw do
  resources :stories

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'home/how_it_works'
  get 'home/deeds'
  get 'home/about'
  get 'home/contactus'
  post 'home/contactus'
  get 'home/privacy'
  get 'home/faq'
  get 'home/wall'
  
  resources :deeds do
    member do
      get 'purchase'
    end
  end
  resources :sponsors
  resources :charities
  resource  :dashboard
  resources  :purchases do
    collection do
      get 'success'
    end
  end
  
  namespace :admin do
    resource :dashboard
    resources :users
    resources  :purchases
    resources :giveons
    resources :deeds do
      member do
        get 'activate'
        get 'cancel'
        get 'freeze'
        get 'spotify'
      end
    end
    resources :stories
    resources :sponsors do
      member do
        get 'verify'
        get 'deny'
      end
    end
    resources :charities
    
  end
  
  root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  belongs_to :user
  has_many :deeds
  validates_presence_of :name
end

app/controllers/admin/charities_controller.rb
class Admin::CharitiesController < Admin::BaseController
  
  def index
    @charities = Charity.page(params[:page]).per(10)
  end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @charities = Charity.page(params[:page]).per(10)
  end
  
  def new
    @charity = Charity.new
  end
  
  def create
    @charity = Charity.new(params[:charity])
    @charity.user = current_user
    if @charity.save
      flash[:info] = "You charity account is successfully created."
      redirect_to dashboard_path
    else
      flash.now[:error] = @charity.errors.full_messages.first
      render :action => 'new'
    end
  end
  
  def show
    @charity = Charity.find(params[:id])
    @deeds = @charity.deeds.completed.page(params[:page]).per(10)
  end
  
  def edit
    @charity = Charity.find(params[:id])
  end
end

app/helpers/admin/charities_helper.rb
module Admin::CharitiesHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/charity/dashboard_helper.rb
module Charity::DashboardHelper
end

app/views/charities/index.html.erb
<h1>Charities</h1>
<div id="charities">
  <ul>
  <% @charities.each do |charity| %>
    <li>
	  <%= link_to image_tag(charity.user.logo.url), charity_path(charity) %><br/>
      <%= link_to charity.name, charity_path(charity) %>
    </li>
  <% end %>
  </ul>
</div>

app/views/charities/new.html.erb
<div class="form_wrapper">
	<div class="form_heading">
		<h5>Create a Charity Account</h5>
	</div><!--end of form_heading-->
	<div class="form_leftwrap">
		<div class="form_rightwrap">
	    	<div class="form_midwrap">
	        	<%= form_for @charity, :url => charities_path do |f| %>
	            	<%= f.label :name %>
	                <div class="textbox_wrapper">
	                	<%= f.text_field :name, :class => "textbox" %>
	                </div><!--end of textbox_wrapper-->
	                <input type="image" src="/images/button_save.png" alt="Save" class="button" />
	            <% end %>
	        </div><!--end of form_midwrap-->
	    </div><!--end of form_rightwrap-->
	</div><!--end of form_leftwrap-->
</div>

app/views/charities/show.html.erb
<div class="content">
	<h1><%= @charity.name %></h1>
	<%= image_tag @charity.user.logo.url %>
	<div class="donations">
		<ul>
		<% @deeds.each do |deed| %>
			<li>Received <%= number_to_currency deed.amount %> donation from <%= image_tag deed.sponsor.user.logo.url %></li>
		<% end %>
		<ul>
	</div>
</div>